# 没有标注为选填项的一律必填，填写时请保证每一项类型一致
# 如果是纯数字的字符串必须使用用''或""括起来
# 以上规则也适用于自动生成的任务配置

users: #用户列表
  - school: # 用户1 学校名称
    username: # 用户1 用户名，一个字符串
    password: # 用户1 密码，一个字符串
    qq: # 用户2 接收推送QQ号，一个数字，选填

  - school: # 用户2 格式同上
    username:
    password:
    qq:

login:
  retryTimes: 5 # 登录重试次数，必须是大于0的数字
  captcha: # 自动打码
    enable: false # 必须是 true 或 false
    pdId:  # 请前往 http://www.fateadm.com 获取，一个字符串，选填
    pdKey: # 请前往 http://www.fateadm.com 获取，一个字符串，选填

noticer: # QQ消息推送
  enable: false # 必须是 true 或 false
  qq: # 负责推送消息的QQ号，一个数字，选填
  password: # 负责推送消息的QQ密码，一个字符串，选填

logLevel: info # 日志级别 debug/info/warn/error
