users: #用户列表
  - school_name: # 用户1 学校名称
    username: # 用户1 用户名
    password: # 用户1 密码
    qq: # 用户2 推送QQ号

  - school_name: # 用户2 学校名称
    username: # 用户2 用户名
    password: # 用户2 密码
    qq: # 用户2 推送QQ号

login:
  retryTimes: 5 # 登录重试次数
  captcha: # 自动打码
    enable: false
    pdId:  # 请前往 http://www.fateadm.com 获取
    pdKey: # 请前往 http://www.fateadm.com 获取

logLevel: info # 日志级别 debug/info/warn/error
